version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DB_URL=postgresql://postgres:testpass123@postgres:5432/mydb
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:testpass123@postgres:5432/mydb
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - EDGE_STORE_ACCESS_KEY=${EDGE_STORE_ACCESS_KEY}
      - EDGE_STORE_SECRET_KEY=${EDGE_STORE_SECRET_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpass123
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: