name: Continuous Deployment (Prod) (Backend)
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            DB_URL=${{ secrets.DATABASE_URL }}
            EDGE_STORE_ACCESS_KEY=${{ secrets.EDGE_STORE_ACCESS_KEY }}
            EDGE_STORE_SECRET_KEY=${{ secrets.EDGE_STORE_SECRET_KEY }}
            NEXT_PUBLIC_GROQ_API_KEY=${{ secrets.NEXT_PUBLIC_GROQ_API_KEY }}
          tags: tusharchawre0240/vishay-blogs:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop and remove the existing container
            sudo docker stop vishay-blogs || true
            sudo docker rm vishay-blogs || true

            # Remove the old image
            sudo docker rmi tusharchawre0240/vishay-blogs:$(docker images -q tusharchawre0240/vishay-blogs) || true

            # Clean up Docker system
            sudo docker system prune -af --volumes
            sudo docker builder prune -af

            # Check disk space
            df -h

            # Pull the new image
            sudo docker pull tusharchawre0240/vishay-blogs:${{ github.sha }}

            # Run the new container with environment variables
            sudo docker run -d \
              --name vishay-blogs \
              -p 3000:3000 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e AUTH_SECRET=${{ secrets.AUTH_SECRET }} \
              -e AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }} \
              -e AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }} \
              -e EDGE_STORE_ACCESS_KEY=${{ secrets.EDGE_STORE_ACCESS_KEY }} \
              -e EDGE_STORE_SECRET_KEY=${{ secrets.EDGE_STORE_SECRET_KEY }} \
              -e GOOGLE_GENERATIVE_AI_API_KEY=${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }} \
              -e NEXT_PUBLIC_GROQ_API_KEY=${{ secrets.NEXT_PUBLIC_GROQ_API_KEY }} \
              -e GROK_API_KEY=${{ secrets.GROK_API_KEY }} \
              tusharchawre0240/vishay-blogs:${{ github.sha }}
